# Generated by Django 3.1.6 on 2021-02-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20210222_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealsourcer',
            name='post_code',
            field=models.CharField(default='d', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealsourcer',
            name='specialized_in',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investor',
            name='post_code',
            field=models.CharField(default='ddd', max_length=255),
            preserve_default=False,
        ),
    ]
