# Generated by Django 3.1.6 on 2021-02-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacesUk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=255)),
                ('destrict', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('postcode', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
