# Generated by Django 3.1.6 on 2021-04-05 18:18

import Deals.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='actual_price',
            field=models.CharField(default='nul', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='bathroom',
            field=models.CharField(default='nukk', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='bedroom',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='epc_rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='key_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='offered_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='postcode',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='real_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='tenure',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='property_investment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deals.propertyinvestmenttype'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deals.propertytype'),
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Deals.models.get_image_filename, verbose_name='Image')),
                ('property_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Deals.property')),
            ],
        ),
    ]
