# Generated by Django 3.1.6 on 2021-03-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0002_placesuk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placesuk',
            old_name='city',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='placesuk',
            old_name='destrict',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='placesuk',
            old_name='region',
            new_name='town_area',
        ),
    ]
