# Generated by Django 3.1.6 on 2021-03-03 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0004_auto_20210303_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ukpostcode',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ukpostcode',
            name='longitude',
        ),
    ]
